### ISSUE TITLE
Realtime move

### ISSUE THREAD

**Issue by mnurulhuda** [bramus/react-native-maps-directions#160]
Can I move the marker while the user is moving and display the movement in realtime ?
because when the user moves the location in Mapview it cannot move in realtime.

Thank you

**Comment by Saturnno** [comment]
For that you just need to use the google directions api directly and use a polyline lib so you can decode it and print it on the map, if you do that with this lib and refresh the route by updating a state varible, it will cost you a lot since every update is a call to google api, be carefull or you will owe your soul to google

**Comment by bramus** [comment]
To draw your actual location on screen, and update it as you move, please check the `reat-native-maps` documentation. This is something outside of the scope of `react-native-maps-directions`.

- Keep a copy of the current location to create the directions using `react-native-maps-directions`
- Draw the current (realtime) location, using the features offered by `react-native-maps`

If you're asking for a 3D navigation as you start driving/walking on a calculated route, check out the https://github.com/flyandi/react-native-maps-navigation project. This is something that falls outside the scope of react-native-maps-directions.
