### ISSUE TITLE
MapViewDirections Error: This IP, site or mobile application is not authorized to use this API key.

### ISSUE THREAD

**Issue by AshwinTayson** [bramus/react-native-maps-directions#64]
Hello,

I'm receiving this error. While I see there are other bugs just like this. You have ignored a very major and fundamental thing. **We are developing for mobile apps.** And in mobile apps we don't keep the API key directly in code. Especially if we use expo, the API key will be configured for the entire project. The library should automatically use the existing KEY in the project. And at present, the library is treating this as a web app and asking for allowed origins whereas it should be checking the SHA code (for Android) configured in the GCP terminal (treat it as a android application). Hope I gave enough information.

**Comment by bramus** [comment]
You're getting the error from the Google Directions API itself because need to pass the API key to the `MapViewDirections` component. Above that you need to configure the API key in the Google Cloud Console and set its restrictions. Not doing so will give the error you mention in the title.

How you get the API key into the app, and how you pass it into `MapViewDirections` component is entirely up to you. I'm unfamiliar with the method you describe in the body of your issue. Feel free to open a PR that implements the way you mention it, and I'll gladly merge it.

**Comment by mancart** [comment]
Im sorry to open this up again but could you maybe tell me which specific API I should set in the restriction list? There just seems to be so many and at this stage I have a working app with Markers etc so the API key I am already passing is working already but still fails if I pass it to MapViewDirections.

Thanks

**Comment by bramus** [comment]
This is described in the readme, in the Basic Usage section: see the description for `apikey`.

**Comment by Vietvantue** [comment]
@bramus Do you have plan to use Mobile SDK for Directions API, since best practices is restrict API KEY by platform: iOS and Android?

**Comment by bramus** [comment]
@Vietvantue As it stands right now this is a pure JavaScript solution. This has the advantage that one doesn't need to include Mobile SDK on iOS.

Regarding the API Keys resrictions: Since this component can be used on both iOS and Android, I restrict the API Key on the APIs it can access: it may only access the Directions API. For the maps themselves I use a separate API Key on Android (and none on iOS since it uses MapKit)

**Comment by marconi** [comment]
Need to update the readme, for future confusions that might arrive here this is what you need to enable:

- Directions API, Maps JavaScript API

**Comment by ngotra2710** [comment]
I got the same error when building an android app using react native

> MapViewDirections Error: Error on GMAPS route request: This IP, site or mobile application is not authorized to use this API key. Request received from IP address xxx.xxx.xxx.xxx, with empty referer

I add Direction API to my Credential > API Keys. However, The key that I use for the react-native-maps doesn't work.
The solution is to create a new API key. Under Set an application restriction, choose None and add Direction API to API restrictions.
![Screenshot from 2023-02-06 19-21-54](https://user-images.githubusercontent.com/43852689/216970513-2d0e557f-54ef-4f2a-b8b0-e3c2ad80b4f5.png)
Finally, Use the new key as prop apikey.
Reference in this link [https://stackoverflow.com/a/58342402/16144717](url)
